In [4]:
import numpy as np
import tensorflow as tf
import pandas as pd
from PIL import Image
from tqdm import tqdm

Фіксимо помилку при завантажені моделі (зроблено для застарілих версіх TensorFlow)

In [5]:
import h5py

f = h5py.File("cards/14card types-14-(200 X 200)-94.61.h5", mode="r+")
model_config_string = f.attrs.get("model_config")

if model_config_string.find('"groups": 1,') != -1:
    model_config_string = model_config_string.replace('"groups": 1,', '')
f.attrs.modify('model_config', model_config_string)
f.flush()

model_config_string = f.attrs.get("model_config")

assert model_config_string.find('"groups": 1,') == -1

In [6]:
model = tf.keras.models.load_model('cards/14card types-14-(200 X 200)-94.61.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\LData\LabsKPI13\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

In [8]:
#model.summary()
# На випадок як забажаєте глянути з чого зроблена модель

In [5]:
# Feature extractor
feature_layer_name = 'dense_6'
feature_extractor = tf.keras.Model(
    inputs=model.inputs,
    outputs=model.get_layer(feature_layer_name).output
)

In [34]:
cards = pd.read_csv('cards/processed_cards.csv')

In [31]:
cards['features'] = [None] * len(cards)  # Initialize an empty column for features
cards['extracted_label'] = [None] * len(cards) # Initialize an empty column for extracted labels

In [35]:
cards['features'] = cards['features'].apply(lambda x: np.fromstring(x[1:-1], sep=' ') if pd.notnull(x) else None)
cards['features'].to_list()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.5492758 , 0.        ,
       0.        , 0.        , 0.        , 0.9262029 , 0.        ,
       0.        , 0.        , 0.09862591, 0.        , 0.        ,
       0.        , 2.7218359 , 0.        , 1.8312975 , 2.5269432 ,
       0.        , 0.        , 0.        , 0.19412917, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04645473,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.6116221 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.72736263, 0.        , 0.        , 0.        ,
       0.4532547 , 0.        , 0.        , 0.        , 0.        ,
       1.8541337 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.29575628, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.9917763 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.8403283 ,
       1.6757518 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01188166, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.9408745 , 0.        , 0.        , 0.        , 1.9530742 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.7922089 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.6211774 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.13215277,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.691376  , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08427185, 0.        ,
       0.        , 0.        , 0.        , 1.9521863 , 1.6475157 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.9289505 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.0268447 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [36]:
cards['features'].to_list()[0][0]

np.float64(0.0)

In [40]:
for i, row in tqdm(cards.iterrows()):
    image_path = row['filepaths']
    image_path = f'cards/{image_path}'
    if row['features'] is not None:
        continue  # Skip if features are already extracted
    try:
        image = Image.open(image_path).convert('RGB')
    except:
        continue
    image = image.resize((200, 200))
    features = feature_extractor(tf.expand_dims(tf.convert_to_tensor(image), axis=0))
    extracted_label = model.predict(tf.expand_dims(tf.convert_to_tensor(image), axis=0)).argmax()
    cards.at[i, 'features'] = features.numpy().flatten()
    cards.at[i, 'extracted_label'] = extracted_label

2717it [00:00, 9898.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 373ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

2717it [00:11, 9898.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3032it [00:11, 168.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3035it [00:14, 127.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3035it [00:31, 127.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3054it [00:31, 39.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3055it [00:32, 38.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

3055it [00:51, 38.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3077it [00:51, 15.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3078it [00:52, 15.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3078it [01:11, 15.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3099it [01:11,  7.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3100it [01:12,  7.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3100it [01:31,  7.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3122it [01:31,  4.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3123it [01:32,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3123it [01:51,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3145it [01:51,  2.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3146it [01:52,  2.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3146it [02:11,  2.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3168it [02:11,  1.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3169it [02:12,  1.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3169it [02:31,  1.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3191it [02:31,  1.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3192it [02:32,  1.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3192it [02:51,  1.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3214it [02:51,  1.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3215it [02:52,  1.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3215it [03:11,  1.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3237it [03:11,  1.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3238it [03:12,  1.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3259it [03:30,  1.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3260it [03:31,  1.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3260it [03:41,  1.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3272it [03:41,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

3273it [03:42,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3283it [03:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3290it [03:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3295it [04:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3299it [04:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3302it [04:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3304it [04:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3306it [04:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3307it [04:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3308it [04:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3309it [04:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3310it [04:14,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3311it [04:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3312it [04:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3313it [04:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3314it [04:18,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3315it [04:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3316it [04:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3317it [04:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3318it [04:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3319it [04:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3320it [04:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3321it [04:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3322it [04:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3323it [04:25,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3324it [04:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3325it [04:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3326it [04:28,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3327it [04:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3328it [04:30,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3329it [04:31,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3330it [04:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3331it [04:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3332it [04:33,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3333it [04:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3334it [04:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3335it [04:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

3336it [04:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3337it [04:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

3338it [04:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3339it [04:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

3340it [04:40,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

3341it [04:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3342it [04:42,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3343it [04:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3344it [04:44,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3345it [04:45,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3346it [04:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3347it [04:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3348it [04:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3349it [04:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3350it [04:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3351it [04:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3352it [04:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3353it [04:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3354it [04:53,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3355it [04:54,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3356it [04:54,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3357it [04:55,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3358it [04:56,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3359it [04:57,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3360it [04:58,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3361it [04:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3362it [05:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3363it [05:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3364it [05:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3365it [05:02,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3366it [05:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3367it [05:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3368it [05:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3369it [05:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3370it [05:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3371it [05:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3372it [05:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3373it [05:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3374it [05:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3375it [05:11,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3376it [05:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3377it [05:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3378it [05:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3379it [05:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3380it [05:15,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3381it [05:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3382it [05:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

3383it [05:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3384it [05:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3385it [05:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3386it [05:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3387it [05:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3388it [05:22,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

3389it [05:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3390it [05:24,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3391it [05:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3392it [05:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3393it [05:27,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3394it [05:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3395it [05:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3396it [05:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3397it [05:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3398it [05:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

3399it [05:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3400it [05:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3401it [05:33,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3402it [05:34,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3403it [05:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3404it [05:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3405it [05:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3406it [05:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3407it [05:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3408it [05:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3409it [05:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3410it [05:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

3411it [05:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3412it [05:43,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3413it [05:44,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3414it [05:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3415it [05:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3416it [05:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3417it [05:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3418it [05:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3419it [05:49,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3420it [05:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3421it [05:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3422it [05:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3423it [05:53,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

3424it [05:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3425it [05:54,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3426it [05:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3427it [05:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3428it [05:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3429it [05:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3430it [05:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3431it [06:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3432it [06:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

3433it [06:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

3434it [06:02,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3435it [06:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3436it [06:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3437it [06:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3438it [06:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3439it [06:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3440it [06:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3441it [06:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3442it [06:09,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3443it [06:10,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3444it [06:11,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3445it [06:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3446it [06:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3447it [06:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3448it [06:14,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3449it [06:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3450it [06:16,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3451it [06:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3452it [06:18,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3453it [06:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

3454it [06:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3455it [06:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3456it [06:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3457it [06:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3458it [06:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3459it [06:24,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3460it [06:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3461it [06:25,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3462it [06:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3463it [06:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3464it [06:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3465it [06:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3466it [06:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3467it [06:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3468it [06:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3469it [06:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3470it [06:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3471it [06:34,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3472it [06:35,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3473it [06:36,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3474it [06:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3475it [06:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

3476it [06:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3477it [06:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3478it [06:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3479it [06:41,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3480it [06:42,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3481it [06:43,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3482it [06:44,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3483it [06:45,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3484it [06:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3485it [06:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3486it [06:47,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3487it [06:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3488it [06:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3489it [06:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3490it [06:51,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3491it [06:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3492it [06:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3493it [06:53,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

3494it [06:54,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

3495it [06:55,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3496it [06:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3497it [06:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

3498it [06:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3499it [06:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3500it [06:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3501it [07:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3502it [07:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3503it [07:02,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3504it [07:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3505it [07:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3506it [07:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

3507it [07:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3508it [07:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3509it [07:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3510it [07:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3511it [07:09,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3512it [07:10,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3513it [07:11,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3514it [07:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3515it [07:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3516it [07:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3517it [07:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3518it [07:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3519it [07:16,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3520it [07:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3521it [07:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3522it [07:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3523it [07:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3524it [07:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3525it [07:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3526it [07:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3527it [07:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3528it [07:24,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3529it [07:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3530it [07:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3531it [07:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3532it [07:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3533it [07:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

3534it [07:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3535it [07:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3536it [07:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3537it [07:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3538it [07:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3539it [07:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3540it [07:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

3541it [07:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3542it [07:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3543it [07:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3544it [07:37,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3545it [07:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3546it [07:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3547it [07:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3548it [07:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3549it [07:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3550it [07:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3551it [07:44,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3552it [07:44,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3553it [07:45,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3554it [07:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3555it [07:47,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3556it [07:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3557it [07:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3558it [07:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3559it [07:51,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3560it [07:51,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3561it [07:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3562it [07:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3563it [07:54,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3564it [07:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3565it [07:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3566it [07:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3567it [07:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3568it [07:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3569it [07:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3570it [08:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3571it [08:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

3572it [08:02,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3573it [08:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3574it [08:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3575it [08:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

3576it [08:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3577it [08:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3578it [08:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3579it [08:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3580it [08:09,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3581it [08:09,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3582it [08:10,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3583it [08:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3584it [08:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3585it [08:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3586it [08:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3587it [08:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3588it [08:16,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3589it [08:16,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3590it [08:17,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3591it [08:18,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3592it [08:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3593it [08:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3594it [08:21,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3595it [08:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3596it [08:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3597it [08:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3598it [08:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3599it [08:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3600it [08:26,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3601it [08:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3602it [08:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3603it [08:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3604it [08:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3605it [08:30,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3606it [08:31,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3607it [08:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3608it [08:33,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3609it [08:34,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3610it [08:34,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3611it [08:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

3612it [08:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3613it [08:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3614it [08:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3615it [08:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3616it [08:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3617it [08:40,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

3618it [08:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

3619it [08:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3620it [08:43,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3621it [08:44,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3622it [08:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3623it [08:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3624it [08:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3625it [08:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3626it [08:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

3627it [08:49,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3628it [08:50,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3629it [08:51,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3630it [08:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3631it [08:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3632it [08:54,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3633it [08:55,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3634it [08:55,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3635it [08:56,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3636it [08:57,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3637it [08:58,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3638it [08:59,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3639it [09:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

3640it [09:01,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3641it [09:02,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3642it [09:03,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3643it [09:04,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3644it [09:04,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3645it [09:05,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

3646it [09:07,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3647it [09:08,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3648it [09:08,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3649it [09:09,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3650it [09:10,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3651it [09:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3652it [09:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3653it [09:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3654it [09:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3655it [09:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3656it [09:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3657it [09:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3658it [09:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3659it [09:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3660it [09:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3661it [09:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3662it [09:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3663it [09:21,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3664it [09:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3665it [09:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3666it [09:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3667it [09:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

3668it [09:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3669it [09:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

3670it [09:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3671it [09:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3672it [09:29,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3673it [09:30,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3674it [09:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3675it [09:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3676it [09:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

3677it [09:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3678it [09:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3679it [09:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3680it [09:36,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

3681it [09:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3682it [09:38,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3683it [09:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3684it [09:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3685it [09:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3686it [09:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3687it [09:42,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3688it [09:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3689it [09:44,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3690it [09:45,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3691it [09:46,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3692it [09:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3693it [09:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3694it [09:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3695it [09:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3696it [09:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3697it [09:51,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3698it [09:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3699it [09:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3700it [09:53,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3701it [09:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3702it [09:55,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3703it [09:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3704it [09:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3705it [09:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3706it [09:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3707it [09:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3708it [10:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3709it [10:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

3710it [10:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3711it [10:03,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3712it [10:04,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3713it [10:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3714it [10:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3715it [10:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3716it [10:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3717it [10:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3718it [10:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3719it [10:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3720it [10:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3721it [10:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3722it [10:12,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3723it [10:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3724it [10:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3725it [10:15,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3726it [10:16,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3727it [10:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3728it [10:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3729it [10:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

3730it [10:19,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3731it [10:20,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3732it [10:21,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3733it [10:22,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3734it [10:23,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3735it [10:24,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3736it [10:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3737it [10:25,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3738it [10:26,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3739it [10:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3740it [10:28,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3741it [10:29,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3742it [10:30,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3743it [10:30,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3744it [10:31,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3745it [10:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3746it [10:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3747it [10:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3748it [10:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3749it [10:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3750it [10:36,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3751it [10:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3752it [10:38,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3753it [10:39,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3754it [10:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3755it [10:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

3756it [10:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3757it [10:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3758it [10:44,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3759it [10:44,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

3760it [10:45,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3761it [10:46,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3762it [10:47,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3763it [10:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3764it [10:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3765it [10:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3766it [10:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3767it [10:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

3768it [10:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3769it [10:53,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3770it [10:54,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3771it [10:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3772it [10:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3773it [10:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3774it [10:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3775it [10:58,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3776it [10:59,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3777it [11:00,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

3778it [11:01,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3779it [11:02,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3780it [11:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3781it [11:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3782it [11:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3783it [11:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3784it [11:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3785it [11:07,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3786it [11:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3787it [11:09,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3788it [11:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3789it [11:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3790it [11:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3791it [11:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3792it [11:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3793it [11:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3794it [11:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3795it [11:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3796it [11:16,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

3797it [11:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3798it [11:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3799it [11:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3800it [11:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3801it [11:21,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

3802it [11:21,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3803it [11:22,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3804it [11:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3805it [11:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3806it [11:25,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3807it [11:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3808it [11:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3809it [11:28,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3810it [11:28,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3811it [11:29,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3812it [11:30,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3813it [11:31,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3814it [11:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3815it [11:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3816it [11:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3817it [11:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3818it [11:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3819it [11:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3820it [11:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3821it [11:38,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3822it [11:39,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3823it [11:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3824it [11:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

3825it [11:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3826it [11:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3827it [11:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3828it [11:44,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3829it [11:45,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3830it [11:46,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3831it [11:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3832it [11:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3833it [11:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3834it [11:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3835it [11:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3836it [11:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3837it [11:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3838it [11:53,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3839it [11:54,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3840it [11:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3841it [11:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3842it [11:56,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

3843it [11:57,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3844it [11:58,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3845it [11:59,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3846it [12:00,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3847it [12:00,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3848it [12:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3849it [12:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3850it [12:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3851it [12:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3852it [12:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3853it [12:06,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3854it [12:07,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3855it [12:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3856it [12:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3857it [12:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3858it [12:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3859it [12:11,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3860it [12:12,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

3861it [12:13,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3862it [12:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3863it [12:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3864it [12:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3865it [12:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3866it [12:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3867it [12:18,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3868it [12:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3869it [12:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3870it [12:20,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3871it [12:21,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3872it [12:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3873it [12:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3874it [12:24,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3875it [12:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3876it [12:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

3877it [12:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3878it [12:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3879it [12:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3880it [12:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3881it [12:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3882it [12:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3883it [12:31,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3884it [12:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3885it [12:33,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3886it [12:34,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3887it [12:35,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3888it [12:36,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3889it [12:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

3890it [12:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3891it [12:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3892it [12:39,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3893it [12:40,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3894it [12:41,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

3895it [12:42,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

3896it [12:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3897it [12:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3898it [12:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3899it [12:45,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3900it [12:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3901it [12:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3902it [12:48,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3903it [12:49,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3904it [12:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3905it [12:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3906it [12:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3907it [12:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3908it [12:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3909it [12:54,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3910it [12:55,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3911it [12:56,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3912it [12:56,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

3913it [12:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3914it [12:58,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3915it [12:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3916it [13:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3917it [13:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

3918it [13:02,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3919it [13:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3920it [13:03,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3921it [13:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3922it [13:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3923it [13:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3924it [13:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3925it [13:08,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3926it [13:09,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3927it [13:09,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3928it [13:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3929it [13:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3930it [13:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3931it [13:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3932it [13:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3933it [13:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3934it [13:15,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3935it [13:16,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

3936it [13:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3937it [13:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3938it [13:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3939it [13:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3940it [13:21,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3941it [13:21,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3942it [13:22,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3943it [13:23,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3944it [13:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3945it [13:25,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3946it [13:26,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3947it [13:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

3948it [13:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3949it [13:28,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3950it [13:29,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3951it [13:30,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3952it [13:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3953it [13:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3954it [13:33,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3955it [13:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

3956it [13:34,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3957it [13:35,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

3958it [13:36,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3959it [13:37,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3960it [13:38,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3961it [13:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

3962it [13:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3963it [13:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

3964it [13:41,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

3965it [13:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3966it [13:43,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3967it [13:44,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3968it [13:45,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3969it [13:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

3970it [13:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3971it [13:47,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

3972it [13:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3973it [13:49,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3974it [13:50,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3975it [13:51,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

3976it [13:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3977it [13:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3978it [13:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

3979it [13:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3980it [13:55,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3981it [13:56,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

3982it [13:57,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3983it [13:58,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

3984it [13:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3985it [13:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

3986it [14:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

3987it [14:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3988it [14:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

3989it [14:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3990it [14:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

3991it [14:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

3992it [14:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3993it [14:06,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

3994it [14:07,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

3995it [14:08,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

3996it [14:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

3997it [14:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

3998it [14:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

3999it [14:12,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

4000it [14:12,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

4001it [14:13,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4002it [14:14,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4003it [14:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4004it [14:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4005it [14:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4006it [14:18,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4007it [14:18,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4008it [14:19,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4009it [14:20,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4010it [14:21,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4011it [14:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

4012it [14:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4013it [14:24,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4014it [14:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4015it [14:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4016it [14:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4017it [14:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4018it [14:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4019it [14:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4020it [14:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4021it [14:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

4022it [14:31,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4023it [14:32,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4024it [14:33,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4025it [14:34,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4026it [14:35,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4027it [14:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4028it [14:36,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4029it [14:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4030it [14:38,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4031it [14:39,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4032it [14:40,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4033it [14:41,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

4034it [14:42,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4035it [14:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4036it [14:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4037it [14:44,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4038it [14:45,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4039it [14:46,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4040it [14:47,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4041it [14:48,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4042it [14:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4043it [14:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4044it [14:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4045it [14:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4046it [14:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4047it [14:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4048it [14:54,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4049it [14:55,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4050it [14:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4051it [14:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

4052it [14:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4053it [14:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4054it [14:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4055it [15:00,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4056it [15:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4057it [15:02,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4058it [15:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4059it [15:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4060it [15:04,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4061it [15:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4062it [15:06,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4063it [15:07,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4064it [15:08,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

4065it [15:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4066it [15:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4067it [15:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4068it [15:11,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4069it [15:12,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

4070it [15:13,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4071it [15:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4072it [15:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4073it [15:15,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4074it [15:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4075it [15:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4076it [15:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4077it [15:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4078it [15:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4079it [15:20,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4080it [15:21,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4081it [15:22,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4082it [15:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4083it [15:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4084it [15:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4085it [15:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

4086it [15:26,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

4087it [15:27,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4088it [15:28,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4089it [15:29,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4090it [15:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4091it [15:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4092it [15:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4093it [15:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4094it [15:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4095it [15:34,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4096it [15:35,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4097it [15:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4098it [15:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4099it [15:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4100it [15:38,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4101it [15:39,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4102it [15:40,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4103it [15:41,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

4104it [15:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4105it [15:43,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4106it [15:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4107it [15:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4108it [15:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4109it [15:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4110it [15:47,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4111it [15:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4112it [15:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4113it [15:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4114it [15:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4115it [15:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

4116it [15:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4117it [15:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4118it [15:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4119it [15:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4120it [15:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4121it [15:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4122it [15:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4123it [15:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4124it [15:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4125it [16:00,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4126it [16:01,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4127it [16:02,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4128it [16:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4129it [16:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4130it [16:05,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4131it [16:05,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4132it [16:06,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

4133it [16:07,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4134it [16:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4135it [16:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4136it [16:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4137it [16:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4138it [16:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4139it [16:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4140it [16:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4141it [16:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4142it [16:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4143it [16:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4144it [16:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4145it [16:18,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4146it [16:18,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4147it [16:19,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4148it [16:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4149it [16:21,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4150it [16:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4151it [16:23,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4152it [16:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4153it [16:24,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4154it [16:25,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4155it [16:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4156it [16:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4157it [16:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4158it [16:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4159it [16:30,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4160it [16:30,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4161it [16:31,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4162it [16:32,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4163it [16:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4164it [16:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4165it [16:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4166it [16:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4167it [16:36,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4168it [16:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4169it [16:38,  1.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4170it [16:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4171it [16:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4172it [16:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4173it [16:42,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4174it [16:43,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4175it [16:43,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4176it [16:44,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4177it [16:45,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4178it [16:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4179it [16:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4180it [16:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4181it [16:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4182it [16:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4183it [16:50,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4184it [16:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4185it [16:52,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4186it [16:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

4187it [16:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4188it [16:55,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4189it [16:55,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4190it [16:56,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4191it [16:57,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4192it [16:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4193it [16:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

4194it [17:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4195it [17:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4196it [17:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4197it [17:02,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4198it [17:03,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4199it [17:04,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4200it [17:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4201it [17:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4202it [17:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4203it [17:07,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4204it [17:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4205it [17:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4206it [17:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4207it [17:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4208it [17:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4209it [17:13,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4210it [17:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4211it [17:14,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4212it [17:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

4213it [17:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4214it [17:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4215it [17:18,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4216it [17:19,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4217it [17:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4218it [17:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4219it [17:23,  1.27s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4220it [17:23,  1.14s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4221it [17:24,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4222it [17:25,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4223it [17:26,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4224it [17:27,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4225it [17:28,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4226it [17:29,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4227it [17:30,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4228it [17:31,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4229it [17:31,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4230it [17:32,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4231it [17:33,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4232it [17:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4233it [17:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4234it [17:36,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4235it [17:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4236it [17:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4237it [17:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4238it [17:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4239it [17:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4240it [17:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

4241it [17:42,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4242it [17:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4243it [17:44,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4244it [17:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4245it [17:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4246it [17:46,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4247it [17:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4248it [17:48,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4249it [17:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4250it [17:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4251it [17:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4252it [17:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4253it [17:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4254it [17:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4255it [17:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4256it [17:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4257it [17:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4258it [17:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4259it [17:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4260it [17:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4261it [18:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4262it [18:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4263it [18:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4264it [18:02,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4265it [18:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4266it [18:04,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4267it [18:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4268it [18:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4269it [18:07,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4270it [18:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4271it [18:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4272it [18:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4273it [18:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4274it [18:11,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4275it [18:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4276it [18:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4277it [18:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4278it [18:14,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4279it [18:15,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4280it [18:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4281it [18:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4282it [18:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4283it [18:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4284it [18:20,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4285it [18:20,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4286it [18:21,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4287it [18:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4288it [18:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

4289it [18:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4290it [18:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4291it [18:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4292it [18:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4293it [18:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4294it [18:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4295it [18:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4296it [18:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4297it [18:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4298it [18:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4299it [18:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4300it [18:34,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4301it [18:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

4302it [18:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4303it [18:36,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4304it [18:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4305it [18:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4306it [18:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4307it [18:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4308it [18:41,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

4309it [18:42,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4310it [18:43,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4311it [18:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4312it [18:45,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4313it [18:45,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4314it [18:46,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4315it [18:47,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4316it [18:48,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4317it [18:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4318it [18:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4319it [18:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4320it [18:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4321it [18:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4322it [18:53,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4323it [18:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4324it [18:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4325it [18:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4326it [18:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4327it [18:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4328it [18:59,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4329it [19:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4330it [19:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4331it [19:01,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

4332it [19:02,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4333it [19:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4334it [19:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4335it [19:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4336it [19:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4337it [19:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

4338it [19:08,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4339it [19:09,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4340it [19:09,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4341it [19:10,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4342it [19:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4343it [19:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4344it [19:13,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4345it [19:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4346it [19:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4347it [19:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4348it [19:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4349it [19:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4350it [19:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4351it [19:19,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4352it [19:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4353it [19:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4354it [19:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4355it [19:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4356it [19:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4357it [19:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4358it [19:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4359it [19:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4360it [19:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4361it [19:28,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4362it [19:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4363it [19:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4364it [19:30,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4365it [19:31,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4366it [19:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4367it [19:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4368it [19:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

4369it [19:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4370it [19:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4371it [19:37,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4372it [19:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4373it [19:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4374it [19:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4375it [19:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

4376it [19:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

4377it [19:42,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4378it [19:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4379it [19:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4380it [19:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4381it [19:45,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4382it [19:46,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4383it [19:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4384it [19:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4385it [19:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4386it [19:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4387it [19:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4388it [19:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4389it [19:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4390it [19:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4391it [19:54,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4392it [19:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4393it [19:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4394it [19:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4395it [19:58,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4396it [19:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4397it [19:59,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4398it [20:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4399it [20:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4400it [20:02,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4401it [20:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

4402it [20:04,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4403it [20:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4404it [20:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4405it [20:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4406it [20:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4407it [20:08,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4408it [20:09,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4409it [20:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4410it [20:11,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4411it [20:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4412it [20:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4413it [20:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4414it [20:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4415it [20:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4416it [20:16,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

4417it [20:17,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4418it [20:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4419it [20:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4420it [20:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4421it [20:20,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4422it [20:21,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4423it [20:22,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4424it [20:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4425it [20:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4426it [20:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4427it [20:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4428it [20:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4429it [20:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4430it [20:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4431it [20:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4432it [20:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4433it [20:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4434it [20:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

4435it [20:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4436it [20:34,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4437it [20:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4438it [20:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4439it [20:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4440it [20:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

4441it [20:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4442it [20:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4443it [20:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4444it [20:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

4445it [20:42,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4446it [20:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4447it [20:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4448it [20:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4449it [20:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4450it [20:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4451it [20:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4452it [20:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4453it [20:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4454it [20:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4455it [20:50,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4456it [20:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

4457it [20:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4458it [20:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4459it [20:54,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4460it [20:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4461it [20:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4462it [20:57,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4463it [20:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4464it [20:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4465it [20:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4466it [21:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4467it [21:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4468it [21:02,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4469it [21:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4470it [21:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4471it [21:04,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4472it [21:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

4473it [21:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4474it [21:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4475it [21:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4476it [21:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4477it [21:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4478it [21:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4479it [21:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4480it [21:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4481it [21:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4482it [21:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4483it [21:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4484it [21:16,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4485it [21:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4486it [21:18,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4487it [21:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4488it [21:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4489it [21:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4490it [21:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4491it [21:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4492it [21:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4493it [21:24,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4494it [21:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4495it [21:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4496it [21:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4497it [21:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4498it [21:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4499it [21:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4500it [21:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4501it [21:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4502it [21:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4503it [21:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4504it [21:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4505it [21:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4506it [21:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4507it [21:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4508it [21:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4509it [21:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4510it [21:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

4511it [21:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4512it [21:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4513it [21:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

4514it [21:42,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4515it [21:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4516it [21:44,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4517it [21:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4518it [21:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4519it [21:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4520it [21:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4521it [21:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4522it [21:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4523it [21:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4524it [21:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4525it [21:52,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4526it [21:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4527it [21:53,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4528it [21:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4529it [21:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4530it [21:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4531it [21:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4532it [21:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4533it [21:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4534it [21:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4535it [22:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4536it [22:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

4537it [22:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4538it [22:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4539it [22:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4540it [22:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4541it [22:06,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4542it [22:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4543it [22:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4544it [22:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4545it [22:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4546it [22:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4547it [22:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4548it [22:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4549it [22:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4550it [22:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4551it [22:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4552it [22:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4553it [22:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4554it [22:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4555it [22:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4556it [22:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4557it [22:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4558it [22:20,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4559it [22:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4560it [22:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4561it [22:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4562it [22:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4563it [22:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4564it [22:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4565it [22:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4566it [22:27,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4567it [22:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4568it [22:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4569it [22:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4570it [22:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4571it [22:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

4572it [22:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4573it [22:34,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4574it [22:34,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4575it [22:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4576it [22:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4577it [22:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4578it [22:38,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4579it [22:39,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4580it [22:40,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4581it [22:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

4582it [22:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4583it [22:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4584it [22:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4585it [22:44,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4586it [22:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4587it [22:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4588it [22:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4589it [22:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4590it [22:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4591it [22:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4592it [22:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4593it [22:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4594it [22:52,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4595it [22:53,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4596it [22:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

4597it [22:55,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4598it [22:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4599it [22:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4600it [22:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4601it [22:58,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4602it [22:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4603it [23:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4604it [23:01,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4605it [23:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4606it [23:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4607it [23:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4608it [23:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4609it [23:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4610it [23:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4611it [23:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4612it [23:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4613it [23:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4614it [23:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

4615it [23:11,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4616it [23:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4617it [23:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4618it [23:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4619it [23:14,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4620it [23:15,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4621it [23:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4622it [23:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4623it [23:17,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4624it [23:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4625it [23:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4626it [23:20,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4627it [23:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4628it [23:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4629it [23:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4630it [23:24,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4631it [23:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4632it [23:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4633it [23:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

4634it [23:27,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4635it [23:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4636it [23:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4637it [23:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4638it [23:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4639it [23:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4640it [23:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4641it [23:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4642it [23:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4643it [23:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4644it [23:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4645it [23:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4646it [23:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4647it [23:38,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4648it [23:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4649it [23:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4650it [23:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4651it [23:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4652it [23:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4653it [23:44,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4654it [23:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4655it [23:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

4656it [23:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4657it [23:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4658it [23:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4659it [23:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4660it [23:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4661it [23:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4662it [23:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4663it [23:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4664it [23:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4665it [23:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4666it [23:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4667it [23:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4668it [23:57,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4669it [23:58,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4670it [23:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4671it [24:00,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4672it [24:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4673it [24:01,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4674it [24:02,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4675it [24:03,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4676it [24:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4677it [24:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4678it [24:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4679it [24:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4680it [24:08,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4681it [24:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4682it [24:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4683it [24:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

4684it [24:11,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4685it [24:12,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4686it [24:13,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4687it [24:14,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4688it [24:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4689it [24:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4690it [24:17,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

4691it [24:17,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4692it [24:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

4693it [24:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4694it [24:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4695it [24:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4696it [24:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4697it [24:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4698it [24:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4699it [24:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4700it [24:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4701it [24:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4702it [24:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4703it [24:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4704it [24:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4705it [24:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4706it [24:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4707it [24:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4708it [24:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4709it [24:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4710it [24:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4711it [24:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4712it [24:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4713it [24:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4714it [24:38,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4715it [24:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4716it [24:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4717it [24:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4718it [24:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

4719it [24:42,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4720it [24:43,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4721it [24:44,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4722it [24:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4723it [24:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4724it [24:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4725it [24:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4726it [24:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4727it [24:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4728it [24:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4729it [24:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4730it [24:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4731it [24:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4732it [24:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4733it [24:54,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4734it [24:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4735it [24:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4736it [24:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4737it [24:58,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4738it [24:59,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4739it [25:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4740it [25:01,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4741it [25:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4742it [25:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4743it [25:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4744it [25:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4745it [25:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4746it [25:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4747it [25:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4748it [25:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4749it [25:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

4750it [25:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4751it [25:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4752it [25:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4753it [25:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4754it [25:13,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4755it [25:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4756it [25:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4757it [25:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4758it [25:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4759it [25:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4760it [25:18,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4761it [25:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4762it [25:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4763it [25:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4764it [25:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4765it [25:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4766it [25:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4767it [25:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4768it [25:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4769it [25:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4770it [25:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4771it [25:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4772it [25:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4773it [25:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4774it [25:30,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4775it [25:31,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4776it [25:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4777it [25:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4778it [25:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4779it [25:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4780it [25:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4781it [25:36,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4782it [25:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4783it [25:38,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4784it [25:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4785it [25:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4786it [25:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

4787it [25:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4788it [25:43,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4789it [25:44,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4790it [25:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4791it [25:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4792it [25:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4793it [25:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4794it [25:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4795it [25:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4796it [25:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4797it [25:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4798it [25:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4799it [25:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4800it [25:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4801it [25:54,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4802it [25:55,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4803it [25:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4804it [25:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4805it [25:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

4806it [25:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4807it [25:59,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4808it [26:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4809it [26:01,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4810it [26:02,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4811it [26:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4812it [26:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4813it [26:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4814it [26:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4815it [26:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4816it [26:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4817it [26:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4818it [26:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4819it [26:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

4820it [26:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4821it [26:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4822it [26:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4823it [26:14,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4824it [26:14,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4825it [26:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4826it [26:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4827it [26:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4828it [26:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4829it [26:19,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4830it [26:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4831it [26:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4832it [26:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4833it [26:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4834it [26:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4835it [26:24,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4836it [26:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4837it [26:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4838it [26:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4839it [26:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4840it [26:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4841it [26:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4842it [26:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4843it [26:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4844it [26:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4845it [26:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4846it [26:34,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4847it [26:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4848it [26:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4849it [26:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4850it [26:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4851it [26:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4852it [26:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4853it [26:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4854it [26:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

4855it [26:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

4856it [26:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4857it [26:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4858it [26:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4859it [26:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4860it [26:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4861it [26:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

4862it [26:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4863it [26:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4864it [26:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4865it [26:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4866it [26:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

4867it [26:52,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4868it [26:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4869it [26:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4870it [26:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4871it [26:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4872it [26:56,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

4873it [26:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4874it [26:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4875it [26:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4876it [27:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4877it [27:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4878it [27:02,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4879it [27:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4880it [27:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4881it [27:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4882it [27:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4883it [27:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4884it [27:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4885it [27:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4886it [27:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4887it [27:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4888it [27:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4889it [27:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

4890it [27:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4891it [27:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4892it [27:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4893it [27:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4894it [27:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4895it [27:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4896it [27:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4897it [27:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4898it [27:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4899it [27:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4900it [27:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4901it [27:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4902it [27:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4903it [27:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4904it [27:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4905it [27:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4906it [27:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4907it [27:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4908it [27:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4909it [27:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4910it [27:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4911it [27:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4912it [27:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4913it [27:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4914it [27:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4915it [27:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4916it [27:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4917it [27:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4918it [27:37,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4919it [27:37,  1.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4920it [27:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4921it [27:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4922it [27:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4923it [27:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4924it [27:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

4925it [27:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4926it [27:44,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4927it [27:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4928it [27:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4929it [27:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4930it [27:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4931it [27:48,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4932it [27:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4933it [27:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4934it [27:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4935it [27:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4936it [27:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4937it [27:54,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4938it [27:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4939it [27:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4940it [27:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4941it [27:57,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4942it [27:58,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4943it [27:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4944it [28:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4945it [28:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4946it [28:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

4947it [28:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4948it [28:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4949it [28:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4950it [28:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4951it [28:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4952it [28:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4953it [28:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

4954it [28:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4955it [28:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4956it [28:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4957it [28:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4958it [28:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4959it [28:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4960it [28:14,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4961it [28:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4962it [28:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4963it [28:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

4964it [28:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

4965it [28:18,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

4966it [28:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4967it [28:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4968it [28:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4969it [28:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

4970it [28:22,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4971it [28:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4972it [28:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4973it [28:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4974it [28:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4975it [28:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

4976it [28:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4977it [28:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4978it [28:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

4979it [28:30,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

4980it [28:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4981it [28:32,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4982it [28:33,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4983it [28:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4984it [28:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4985it [28:35,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

4986it [28:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

4987it [28:37,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4988it [28:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

4989it [28:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

4990it [28:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

4991it [28:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

4992it [28:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

4993it [28:43,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

4994it [28:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4995it [28:45,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

4996it [28:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

4997it [28:46,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4998it [28:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

4999it [28:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5000it [28:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5001it [28:50,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5002it [28:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5003it [28:51,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5004it [28:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5005it [28:53,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5006it [28:54,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5007it [28:55,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5008it [28:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5009it [28:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5010it [28:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5011it [28:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5012it [28:59,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5013it [29:00,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5014it [29:01,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5015it [29:02,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5016it [29:03,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5017it [29:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5018it [29:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5019it [29:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5020it [29:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5021it [29:07,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5022it [29:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5023it [29:09,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5024it [29:10,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5025it [29:11,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5026it [29:12,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5027it [29:13,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5028it [29:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5029it [29:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5030it [29:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5031it [29:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5032it [29:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5033it [29:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5034it [29:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5035it [29:20,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5036it [29:21,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5037it [29:21,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5038it [29:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5039it [29:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5040it [29:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5041it [29:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5042it [29:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5043it [29:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5044it [29:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5045it [29:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5046it [29:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5047it [29:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5048it [29:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5049it [29:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5050it [29:33,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5051it [29:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5052it [29:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

5053it [29:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5054it [29:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5055it [29:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5056it [29:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5057it [29:39,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5058it [29:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5059it [29:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

5060it [29:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5061it [29:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5062it [29:43,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5063it [29:44,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5064it [29:45,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5065it [29:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5066it [29:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5067it [29:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5068it [29:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5069it [29:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5070it [29:50,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5071it [29:51,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5072it [29:52,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5073it [29:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5074it [29:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5075it [29:55,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5076it [29:55,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5077it [29:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5078it [29:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5079it [29:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5080it [29:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5081it [30:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5082it [30:01,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5083it [30:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5084it [30:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5085it [30:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5086it [30:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5087it [30:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5088it [30:06,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5089it [30:07,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5090it [30:08,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

5091it [30:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5092it [30:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5093it [30:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5094it [30:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5095it [30:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5096it [30:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

5097it [30:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5098it [30:15,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5099it [30:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5100it [30:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5101it [30:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5102it [30:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5103it [30:19,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5104it [30:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5105it [30:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

5106it [30:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5107it [30:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5108it [30:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5109it [30:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5110it [30:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5111it [30:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5112it [30:27,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5113it [30:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5114it [30:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5115it [30:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5116it [30:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

5117it [30:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5118it [30:32,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5119it [30:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5120it [30:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5121it [30:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5122it [30:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5123it [30:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5124it [30:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5125it [30:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5126it [30:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5127it [30:40,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5128it [30:41,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

5129it [30:42,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5130it [30:43,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5131it [30:44,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5132it [30:45,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5133it [30:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5134it [30:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5135it [30:47,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5136it [30:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5137it [30:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5138it [30:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5139it [30:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5140it [30:52,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5141it [30:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5142it [30:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5143it [30:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5144it [30:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5145it [30:56,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5146it [30:57,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5147it [30:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5148it [30:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5149it [31:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5150it [31:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5151it [31:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5152it [31:02,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5153it [31:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5154it [31:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5155it [31:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5156it [31:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5157it [31:07,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5158it [31:08,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5159it [31:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5160it [31:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5161it [31:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5162it [31:11,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5163it [31:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5164it [31:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5165it [31:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5166it [31:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5167it [31:16,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5168it [31:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

5169it [31:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5170it [31:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5171it [31:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5172it [31:20,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5173it [31:21,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5174it [31:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5175it [31:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5176it [31:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5177it [31:24,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5178it [31:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5179it [31:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5180it [31:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5181it [31:28,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5182it [31:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5183it [31:30,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5184it [31:30,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5185it [31:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5186it [31:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5187it [31:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5188it [31:34,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

5189it [31:35,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5190it [31:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5191it [31:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5192it [31:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5193it [31:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5194it [31:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5195it [31:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5196it [31:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

5197it [31:42,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5198it [31:43,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5199it [31:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5200it [31:45,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5201it [31:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5202it [31:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5203it [31:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5204it [31:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5205it [31:49,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5206it [31:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5207it [31:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5208it [31:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5209it [31:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5210it [31:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5211it [31:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5212it [31:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5213it [31:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

5214it [31:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5215it [31:58,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5216it [31:59,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5217it [32:00,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5218it [32:01,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

5219it [32:02,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5220it [32:02,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

5221it [32:03,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5222it [32:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5223it [32:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5224it [32:06,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5225it [32:07,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5226it [32:08,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5227it [32:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5228it [32:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5229it [32:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5230it [32:11,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5231it [32:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5232it [32:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5233it [32:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5234it [32:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5235it [32:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5236it [32:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5237it [32:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5238it [32:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5239it [32:19,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5240it [32:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5241it [32:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5242it [32:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5243it [32:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

5244it [32:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5245it [32:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5246it [32:25,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5247it [32:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5248it [32:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5249it [32:28,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5250it [32:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5251it [32:30,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5252it [32:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5253it [32:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5254it [32:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5255it [32:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5256it [32:34,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5257it [32:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5258it [32:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5259it [32:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5260it [32:37,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5261it [32:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5262it [32:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5263it [32:40,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5264it [32:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

5265it [32:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5266it [32:43,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5267it [32:44,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5268it [32:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5269it [32:46,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5270it [32:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5271it [32:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5272it [32:48,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5273it [32:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step

5274it [32:50,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5275it [32:51,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5276it [32:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5277it [32:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5278it [32:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5279it [32:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5280it [32:55,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5281it [32:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5282it [32:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5283it [32:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5284it [32:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5285it [33:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5286it [33:01,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5287it [33:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5288it [33:02,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

5289it [33:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5290it [33:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5291it [33:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5292it [33:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5293it [33:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5294it [33:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5295it [33:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5296it [33:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5297it [33:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5298it [33:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5299it [33:12,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5300it [33:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

5301it [33:14,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5302it [33:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5303it [33:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5304it [33:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5305it [33:17,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5306it [33:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5307it [33:19,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5308it [33:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5309it [33:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5310it [33:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5311it [33:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5312it [33:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5313it [33:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5314it [33:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5315it [33:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5316it [33:27,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5317it [33:28,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5318it [33:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5319it [33:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5320it [33:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5321it [33:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5322it [33:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5323it [33:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5324it [33:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5325it [33:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5326it [33:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5327it [33:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5328it [33:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5329it [33:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5330it [33:39,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5331it [33:40,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5332it [33:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

5333it [33:42,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5334it [33:43,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5335it [33:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5336it [33:45,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

5337it [33:46,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5338it [33:47,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5339it [33:48,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5340it [33:48,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5341it [33:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5342it [33:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5343it [33:51,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5344it [33:52,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5345it [33:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5346it [33:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5347it [33:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5348it [33:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5349it [33:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5350it [33:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5351it [33:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5352it [33:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5353it [34:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5354it [34:01,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5355it [34:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5356it [34:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5357it [34:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5358it [34:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5359it [34:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5360it [34:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5361it [34:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5362it [34:08,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5363it [34:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5364it [34:10,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

5365it [34:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5366it [34:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5367it [34:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5368it [34:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5369it [34:14,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5370it [34:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5371it [34:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5372it [34:16,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5373it [34:17,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5374it [34:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5375it [34:19,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5376it [34:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5377it [34:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5378it [34:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5379it [34:23,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5380it [34:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5381it [34:24,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5382it [34:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5383it [34:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5384it [34:27,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5385it [34:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5386it [34:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

5387it [34:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5388it [34:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5389it [34:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5390it [34:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5391it [34:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5392it [34:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5393it [34:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5394it [34:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5395it [34:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

5396it [34:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5397it [34:38,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5398it [34:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5399it [34:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5400it [34:41,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

5401it [34:42,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5402it [34:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5403it [34:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5404it [34:45,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5405it [34:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5406it [34:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5407it [34:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5408it [34:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5409it [34:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5410it [34:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5411it [34:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5412it [34:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5413it [34:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5414it [34:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5415it [34:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5416it [34:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5417it [34:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5418it [34:57,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5419it [34:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5420it [34:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5421it [35:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5422it [35:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5423it [35:01,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5424it [35:02,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5425it [35:03,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5426it [35:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5427it [35:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5428it [35:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5429it [35:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5430it [35:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5431it [35:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5432it [35:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5433it [35:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5434it [35:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

5435it [35:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5436it [35:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5437it [35:14,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5438it [35:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5439it [35:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5440it [35:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5441it [35:17,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5442it [35:18,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5443it [35:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5444it [35:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5445it [35:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5446it [35:22,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5447it [35:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5448it [35:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5449it [35:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5450it [35:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5451it [35:26,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5452it [35:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5453it [35:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5454it [35:29,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5455it [35:29,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5456it [35:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5457it [35:31,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5458it [35:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5459it [35:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5460it [35:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5461it [35:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5462it [35:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5463it [35:37,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5464it [35:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5465it [35:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5466it [35:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5467it [35:40,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5468it [35:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

5469it [35:42,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5470it [35:43,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5471it [35:44,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5472it [35:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5473it [35:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5474it [35:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5475it [35:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5476it [35:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5477it [35:49,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5478it [35:50,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

5479it [35:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

5480it [35:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5481it [35:52,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

5482it [35:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5483it [35:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5484it [35:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5485it [35:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5486it [35:57,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5487it [35:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5488it [35:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5489it [35:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5490it [36:00,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5491it [36:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5492it [36:02,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5493it [36:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5494it [36:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5495it [36:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5496it [36:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5497it [36:07,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5498it [36:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5499it [36:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5500it [36:09,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5501it [36:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5502it [36:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5503it [36:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5504it [36:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5505it [36:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5506it [36:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5507it [36:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5508it [36:16,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5509it [36:17,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5510it [36:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5511it [36:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5512it [36:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5513it [36:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5514it [36:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5515it [36:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5516it [36:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5517it [36:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5518it [36:25,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5519it [36:26,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5520it [36:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5521it [36:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5522it [36:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5523it [36:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5524it [36:30,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5525it [36:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5526it [36:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5527it [36:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5528it [36:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5529it [36:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5530it [36:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5531it [36:36,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5532it [36:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5533it [36:38,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5534it [36:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5535it [36:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5536it [36:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5537it [36:42,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

5538it [36:43,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5539it [36:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5540it [36:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5541it [36:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5542it [36:46,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5543it [36:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5544it [36:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5545it [36:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5546it [36:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5547it [36:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5548it [36:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5549it [36:52,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5550it [36:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5551it [36:54,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5552it [36:55,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5553it [36:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5554it [36:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5555it [36:58,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5556it [36:59,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5557it [36:59,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5558it [37:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5559it [37:01,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5560it [37:02,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5561it [37:03,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5562it [37:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5563it [37:05,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5564it [37:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5565it [37:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5566it [37:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5567it [37:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5568it [37:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5569it [37:10,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5570it [37:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5571it [37:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5572it [37:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5573it [37:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5574it [37:14,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5575it [37:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5576it [37:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5577it [37:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5578it [37:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5579it [37:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5580it [37:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5581it [37:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5582it [37:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5583it [37:22,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5584it [37:23,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5585it [37:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5586it [37:25,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5587it [37:26,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5588it [37:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5589it [37:27,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5590it [37:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5591it [37:29,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5592it [37:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5593it [37:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5594it [37:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5595it [37:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5596it [37:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5597it [37:35,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5598it [37:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5599it [37:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5600it [37:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5601it [37:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5602it [37:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5603it [37:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5604it [37:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

5605it [37:42,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5606it [37:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5607it [37:43,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5608it [37:44,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5609it [37:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5610it [37:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5611it [37:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5612it [37:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5613it [37:49,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5614it [37:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5615it [37:50,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5616it [37:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5617it [37:52,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5618it [37:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5619it [37:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5620it [37:55,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5621it [37:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5622it [37:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5623it [37:57,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5624it [37:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5625it [37:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5626it [38:00,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5627it [38:01,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5628it [38:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5629it [38:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5630it [38:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5631it [38:05,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5632it [38:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5633it [38:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5634it [38:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5635it [38:08,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5636it [38:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5637it [38:10,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5638it [38:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5639it [38:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5640it [38:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5641it [38:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

5642it [38:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5643it [38:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5644it [38:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5645it [38:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5646it [38:18,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5647it [38:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5648it [38:20,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5649it [38:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5650it [38:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5651it [38:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5652it [38:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5653it [38:24,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5654it [38:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5655it [38:26,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5656it [38:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5657it [38:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5658it [38:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5659it [38:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5660it [38:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5661it [38:31,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5662it [38:32,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5663it [38:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5664it [38:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5665it [38:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5666it [38:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5667it [38:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5668it [38:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5669it [38:38,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5670it [38:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5671it [38:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5672it [38:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step

5673it [38:41,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5674it [38:43,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5675it [38:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5676it [38:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5677it [38:45,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5678it [38:46,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5679it [38:47,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5680it [38:48,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5681it [38:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5682it [38:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5683it [38:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5684it [38:51,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5685it [38:52,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5686it [38:53,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5687it [38:54,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5688it [38:55,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5689it [38:56,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5690it [38:57,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5691it [38:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5692it [38:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5693it [38:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

5694it [39:00,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5695it [39:01,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5696it [39:02,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5697it [39:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5698it [39:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5699it [39:05,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5700it [39:06,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5701it [39:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5702it [39:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5703it [39:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

5704it [39:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5705it [39:10,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5706it [39:11,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5707it [39:12,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5708it [39:13,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5709it [39:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5710it [39:15,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5711it [39:16,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5712it [39:17,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5713it [39:18,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5714it [39:18,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5715it [39:19,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5716it [39:20,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5717it [39:21,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5718it [39:22,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5719it [39:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5720it [39:24,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5721it [39:25,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5722it [39:26,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5723it [39:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5724it [39:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5725it [39:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5726it [39:29,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5727it [39:30,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5728it [39:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5729it [39:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5730it [39:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5731it [39:34,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5732it [39:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

5733it [39:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5734it [39:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5735it [39:37,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5736it [39:38,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5737it [39:39,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5738it [39:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5739it [39:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

5740it [39:42,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5741it [39:43,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5742it [39:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5743it [39:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5744it [39:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5745it [39:46,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5746it [39:47,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5747it [39:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5748it [39:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5749it [39:50,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5750it [39:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5751it [39:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5752it [39:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5753it [39:53,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5754it [39:54,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5755it [39:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5756it [39:56,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5757it [39:57,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5758it [39:58,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5759it [39:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5760it [39:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5761it [40:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5762it [40:01,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5763it [40:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5764it [40:03,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5765it [40:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5766it [40:05,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5767it [40:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5768it [40:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5769it [40:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5770it [40:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5771it [40:09,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5772it [40:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

5773it [40:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5774it [40:12,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5775it [40:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5776it [40:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5777it [40:14,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

5778it [40:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5779it [40:16,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5780it [40:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5781it [40:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5782it [40:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5783it [40:20,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5784it [40:21,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5785it [40:21,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5786it [40:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5787it [40:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5788it [40:24,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5789it [40:25,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5790it [40:26,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5791it [40:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5792it [40:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

5793it [40:29,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5794it [40:29,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5795it [40:30,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5796it [40:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5797it [40:32,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5798it [40:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5799it [40:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5800it [40:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5801it [40:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5802it [40:36,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5803it [40:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5804it [40:38,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5805it [40:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5806it [40:40,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5807it [40:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

5808it [40:42,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5809it [40:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5810it [40:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5811it [40:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5812it [40:46,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5813it [40:46,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5814it [40:47,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5815it [40:48,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5816it [40:49,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5817it [40:50,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5818it [40:51,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5819it [40:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

5820it [40:53,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5821it [40:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5822it [40:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5823it [40:55,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5824it [40:56,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5825it [40:57,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5826it [40:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5827it [40:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

5828it [41:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5829it [41:01,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5830it [41:02,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5831it [41:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5832it [41:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5833it [41:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5834it [41:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5835it [41:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5836it [41:07,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5837it [41:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5838it [41:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5839it [41:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5840it [41:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5841it [41:11,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5842it [41:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5843it [41:13,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

5844it [41:14,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5845it [41:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5846it [41:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5847it [41:17,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5848it [41:17,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5849it [41:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5850it [41:19,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5851it [41:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5852it [41:21,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5853it [41:22,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5854it [41:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5855it [41:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5856it [41:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5857it [41:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5858it [41:26,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5859it [41:27,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5860it [41:28,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5861it [41:29,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5862it [41:30,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5863it [41:31,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5864it [41:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5865it [41:32,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5866it [41:33,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5867it [41:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5868it [41:35,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5869it [41:36,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5870it [41:37,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5871it [41:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5872it [41:38,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5873it [41:39,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5874it [41:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5875it [41:41,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5876it [41:42,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5877it [41:43,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

5878it [41:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5879it [41:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5880it [41:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5881it [41:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5882it [41:47,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5883it [41:48,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5884it [41:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5885it [41:50,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5886it [41:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5887it [41:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5888it [41:53,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5889it [41:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5890it [41:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5891it [41:55,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5892it [41:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5893it [41:57,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5894it [41:58,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5895it [41:59,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5896it [42:00,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5897it [42:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5898it [42:02,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5899it [42:02,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5900it [42:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5901it [42:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5902it [42:05,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

5903it [42:06,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5904it [42:07,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5905it [42:08,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5906it [42:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5907it [42:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5908it [42:10,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5909it [42:11,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5910it [42:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5911it [42:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5912it [42:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5913it [42:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

5914it [42:16,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5915it [42:17,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5916it [42:17,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

5917it [42:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5918it [42:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5919it [42:20,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5920it [42:21,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5921it [42:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5922it [42:23,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5923it [42:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5924it [42:24,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5925it [42:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5926it [42:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5927it [42:27,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5928it [42:28,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5929it [42:29,  1.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5930it [42:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5931it [42:31,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5932it [42:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5933it [42:32,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5934it [42:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5935it [42:34,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5936it [42:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5937it [42:36,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5938it [42:37,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5939it [42:38,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5940it [42:38,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5941it [42:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

5942it [42:40,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

5943it [42:41,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

5944it [42:42,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5945it [42:43,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5946it [42:44,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5947it [42:45,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5948it [42:46,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5949it [42:47,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5950it [42:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

5951it [42:49,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5952it [42:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5953it [42:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5954it [42:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5955it [42:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5956it [42:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5957it [42:54,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5958it [42:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

5959it [42:56,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

5960it [42:56,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5961it [42:57,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5962it [42:58,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5963it [42:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5964it [43:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

5965it [43:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5966it [43:02,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5967it [43:03,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5968it [43:04,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5969it [43:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5970it [43:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5971it [43:06,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5972it [43:07,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

5973it [43:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

5974it [43:09,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5975it [43:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

5976it [43:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5977it [43:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5978it [43:12,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

5979it [43:13,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5980it [43:14,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5981it [43:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

5982it [43:16,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

5983it [43:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5984it [43:18,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

5985it [43:19,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5986it [43:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

5987it [43:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5988it [43:21,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

5989it [43:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

5990it [43:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

5991it [43:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5992it [43:25,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5993it [43:26,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

5994it [43:26,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

5995it [43:27,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5996it [43:28,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

5997it [43:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

5998it [43:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

5999it [43:31,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6000it [43:32,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6001it [43:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6002it [43:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6003it [43:34,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6004it [43:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6005it [43:36,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6006it [43:37,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6007it [43:38,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6008it [43:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6009it [43:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6010it [43:41,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

6011it [43:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6012it [43:43,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6013it [43:44,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6014it [43:44,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6015it [43:45,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6016it [43:46,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6017it [43:47,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6018it [43:48,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6019it [43:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6020it [43:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6021it [43:51,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6022it [43:52,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6023it [43:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6024it [43:53,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6025it [43:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6026it [43:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6027it [43:56,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6028it [43:57,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6029it [43:58,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6030it [43:59,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6031it [43:59,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6032it [44:00,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6033it [44:01,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6034it [44:02,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6035it [44:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6036it [44:04,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6037it [44:05,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6038it [44:06,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6039it [44:07,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6040it [44:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6041it [44:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6042it [44:09,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6043it [44:10,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6044it [44:11,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6045it [44:12,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6046it [44:13,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6047it [44:14,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6048it [44:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6049it [44:15,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6050it [44:16,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

6051it [44:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6052it [44:18,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6053it [44:19,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6054it [44:20,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6055it [44:21,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6056it [44:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6057it [44:22,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6058it [44:23,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6059it [44:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6060it [44:25,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6061it [44:26,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6062it [44:27,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6063it [44:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6064it [44:29,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6065it [44:30,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6066it [44:30,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6067it [44:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6068it [44:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6069it [44:33,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6070it [44:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

6071it [44:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6072it [44:36,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

6073it [44:37,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6074it [44:38,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

6075it [44:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6076it [44:39,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6077it [44:40,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6078it [44:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6079it [44:42,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6080it [44:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6081it [44:44,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6082it [44:45,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6083it [44:46,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6084it [44:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6085it [44:47,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6086it [44:48,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6087it [44:49,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6088it [44:50,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6089it [44:51,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6090it [44:52,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6091it [44:53,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6092it [44:54,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6093it [44:54,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6094it [44:55,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6095it [44:56,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6096it [44:57,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

6097it [44:58,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6098it [44:59,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6099it [45:00,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6100it [45:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6101it [45:01,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6102it [45:02,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6103it [45:03,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6104it [45:04,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6105it [45:05,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6106it [45:06,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6107it [45:07,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6108it [45:08,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6109it [45:08,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6110it [45:09,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6111it [45:10,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6112it [45:11,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6113it [45:12,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6114it [45:13,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6115it [45:14,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6116it [45:15,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6117it [45:15,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6118it [45:16,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6119it [45:17,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6120it [45:18,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6121it [45:19,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6122it [45:20,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6123it [45:21,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6124it [45:22,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6125it [45:22,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6126it [45:23,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6127it [45:24,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6128it [45:25,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6129it [45:26,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6130it [45:27,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

6131it [45:28,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6132it [45:29,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6133it [45:30,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6134it [45:30,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

6135it [45:31,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6136it [45:32,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6137it [45:33,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6138it [45:34,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6139it [45:35,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6140it [45:36,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6141it [45:37,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6142it [45:38,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6143it [45:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6144it [45:39,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6145it [45:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6146it [45:41,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6147it [45:42,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6148it [45:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6149it [45:44,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6150it [45:45,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6151it [45:46,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6152it [45:47,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6153it [45:48,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

6154it [45:48,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6155it [45:49,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6156it [45:50,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6157it [45:51,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6158it [45:52,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6159it [45:53,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6160it [45:54,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6161it [45:55,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6162it [45:56,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6163it [45:57,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6164it [45:57,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6165it [45:58,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6166it [45:59,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6167it [46:00,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6168it [46:01,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6169it [46:02,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6170it [46:03,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6171it [46:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6172it [46:04,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6173it [46:05,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6174it [46:06,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6175it [46:07,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6176it [46:08,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6177it [46:09,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6178it [46:10,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6179it [46:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6180it [46:11,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6181it [46:12,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

6182it [46:13,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6183it [46:14,  1.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6184it [46:15,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6185it [46:16,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6186it [46:17,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6187it [46:18,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6188it [46:19,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

6189it [46:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6190it [46:20,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6191it [46:21,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6192it [46:22,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6193it [46:23,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6194it [46:24,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6195it [46:25,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6196it [46:25,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6197it [46:26,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6198it [46:27,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6199it [46:28,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6200it [46:29,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6201it [46:30,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6202it [46:31,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6203it [46:32,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6204it [46:33,  1.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6205it [46:33,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6206it [46:34,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6207it [46:35,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

6208it [46:36,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6209it [46:37,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6210it [46:38,  1.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6211it [46:39,  1.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6212it [46:40,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6213it [46:40,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

6214it [46:41,  1.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6215it [46:42,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6216it [46:43,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6217it [46:44,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6218it [46:45,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

6219it [46:46,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6220it [46:47,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6221it [46:49,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6222it [46:50,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

6223it [46:51,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

6224it [46:52,  1.18s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6225it [46:54,  1.37s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6226it [46:55,  1.41s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6227it [46:57,  1.35s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6228it [46:58,  1.28s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6229it [46:59,  1.21s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step

6230it [47:00,  1.22s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

6231it [47:02,  1.29s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6232it [47:03,  1.27s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

6233it [47:04,  1.25s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

6234it [47:05,  1.21s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6235it [47:06,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6236it [47:07,  1.10s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

6237it [47:08,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

6238it [47:09,  1.14s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step

6239it [47:11,  1.18s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

6240it [47:12,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6241it [47:13,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6242it [47:14,  1.19s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

6243it [47:15,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6244it [47:16,  1.13s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6245it [47:18,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6246it [47:18,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6247it [47:19,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6248it [47:21,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6249it [47:22,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6250it [47:22,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6251it [47:23,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6252it [47:24,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6253it [47:25,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6254it [47:26,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6255it [47:27,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6256it [47:28,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6257it [47:29,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

6258it [47:30,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6259it [47:32,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6260it [47:33,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6261it [47:34,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6262it [47:34,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

6263it [47:35,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6264it [47:36,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6265it [47:37,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6266it [47:38,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6267it [47:39,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6268it [47:40,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6269it [47:41,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6270it [47:42,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6271it [47:43,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6272it [47:44,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6273it [47:45,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6274it [47:46,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6275it [47:47,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6276it [47:48,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6277it [47:49,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6278it [47:50,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6279it [47:51,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6280it [47:52,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6281it [47:53,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6282it [47:54,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6283it [47:55,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6284it [47:56,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6285it [47:57,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6286it [47:58,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6287it [47:59,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6288it [47:59,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6289it [48:00,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6290it [48:01,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6291it [48:02,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6292it [48:03,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6293it [48:04,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6294it [48:05,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6295it [48:06,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6296it [48:07,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6297it [48:08,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6298it [48:09,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6299it [48:10,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6300it [48:11,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6301it [48:12,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6302it [48:13,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step

6303it [48:14,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6304it [48:15,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6305it [48:16,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6306it [48:17,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6307it [48:18,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6308it [48:19,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6309it [48:20,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6310it [48:21,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6311it [48:22,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6312it [48:23,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6313it [48:24,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6314it [48:24,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6315it [48:25,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6316it [48:26,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6317it [48:27,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6318it [48:28,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6319it [48:29,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6320it [48:30,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6321it [48:31,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

6322it [48:32,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6323it [48:33,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6324it [48:34,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6325it [48:35,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6326it [48:36,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6327it [48:37,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6328it [48:38,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6329it [48:39,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

6330it [48:40,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6331it [48:41,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step

6332it [48:42,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6333it [48:43,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6334it [48:44,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6335it [48:45,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6336it [48:46,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6337it [48:47,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step

6338it [48:48,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6339it [48:49,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6340it [48:50,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6341it [48:51,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6342it [48:52,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6343it [48:53,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6344it [48:54,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6345it [48:55,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6346it [48:56,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6347it [48:57,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6348it [48:58,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6349it [48:59,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6350it [49:00,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

6351it [49:01,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step

6352it [49:03,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6353it [49:04,  1.29s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6354it [49:05,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6355it [49:06,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6356it [49:07,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

6357it [49:08,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6358it [49:09,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6359it [49:10,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6360it [49:11,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6361it [49:12,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6362it [49:13,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6363it [49:14,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6364it [49:15,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

6365it [49:16,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6366it [49:16,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6367it [49:17,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6368it [49:18,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6369it [49:19,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6370it [49:20,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6371it [49:21,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6372it [49:22,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6373it [49:23,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

6374it [49:24,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6375it [49:25,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6376it [49:26,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6377it [49:27,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

6378it [49:28,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6379it [49:29,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6380it [49:30,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

6381it [49:31,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6382it [49:32,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6383it [49:33,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6384it [49:34,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6385it [49:35,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 361ms/step

6386it [49:37,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

6387it [49:38,  1.19s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

6388it [49:40,  1.39s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6389it [49:41,  1.27s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

6390it [49:42,  1.24s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6391it [49:43,  1.22s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

6392it [49:44,  1.21s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6393it [49:45,  1.21s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6394it [49:47,  1.17s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6395it [49:48,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6396it [49:49,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

6397it [49:50,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6398it [49:51,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6399it [49:52,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6400it [49:53,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step

6401it [49:54,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6402it [49:55,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

6403it [49:56,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6404it [49:57,  1.21s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6405it [49:59,  1.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

6406it [50:00,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

6407it [50:01,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6408it [50:02,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6409it [50:03,  1.14s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6410it [50:04,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6411it [50:05,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6412it [50:06,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6413it [50:07,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6414it [50:08,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6415it [50:09,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6416it [50:10,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6417it [50:11,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6418it [50:12,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6419it [50:13,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6420it [50:14,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6421it [50:15,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6422it [50:16,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6423it [50:17,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6424it [50:18,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6425it [50:19,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6426it [50:20,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6427it [50:21,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6428it [50:22,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6429it [50:23,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6430it [50:24,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6431it [50:25,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6432it [50:26,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6433it [50:27,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6434it [50:28,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6435it [50:29,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6436it [50:30,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

6437it [50:31,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6438it [50:31,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6439it [50:32,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6440it [50:34,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6441it [50:34,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6442it [50:35,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6443it [50:36,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6444it [50:37,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6445it [50:38,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6446it [50:39,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6447it [50:40,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6448it [50:41,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6449it [50:42,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6450it [50:43,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6451it [50:44,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6452it [50:45,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6453it [50:46,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6454it [50:47,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6455it [50:48,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6456it [50:49,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6457it [50:50,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6458it [50:51,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6459it [50:52,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6460it [50:53,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6461it [50:54,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6462it [50:54,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6463it [50:55,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6464it [50:56,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6465it [50:57,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6466it [50:58,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6467it [50:59,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6468it [51:00,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6469it [51:01,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6470it [51:02,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6471it [51:03,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6472it [51:04,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6473it [51:05,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6474it [51:06,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6475it [51:07,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6476it [51:08,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6477it [51:09,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6478it [51:10,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6479it [51:10,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6480it [51:11,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6481it [51:12,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 290ms/step

6482it [51:13,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

6483it [51:14,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6484it [51:16,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6485it [51:16,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6486it [51:18,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6487it [51:19,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6488it [51:20,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6489it [51:21,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6490it [51:22,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6491it [51:23,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6492it [51:24,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6493it [51:25,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6494it [51:26,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

6495it [51:27,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6496it [51:28,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6497it [51:29,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6498it [51:30,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6499it [51:31,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6500it [51:32,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6501it [51:33,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6502it [51:34,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6503it [51:35,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6504it [51:36,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6505it [51:37,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6506it [51:38,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6507it [51:39,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6508it [51:40,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6509it [51:41,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6510it [51:42,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6511it [51:43,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6512it [51:44,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6513it [51:45,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6514it [51:47,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6515it [51:48,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6516it [51:49,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

6517it [51:50,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6518it [51:51,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6519it [51:52,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6520it [51:52,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6521it [51:53,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6522it [51:54,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6523it [51:56,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6524it [51:57,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6525it [51:58,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6526it [51:59,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6527it [52:00,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6528it [52:01,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

6529it [52:02,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

6530it [52:03,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6531it [52:04,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6532it [52:05,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6533it [52:06,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6534it [52:07,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6535it [52:08,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6536it [52:09,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6537it [52:10,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6538it [52:11,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6539it [52:12,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6540it [52:13,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6541it [52:14,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6542it [52:15,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6543it [52:16,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6544it [52:17,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6545it [52:18,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6546it [52:19,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6547it [52:20,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6548it [52:21,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6549it [52:22,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6550it [52:23,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6551it [52:24,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6552it [52:25,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6553it [52:26,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6554it [52:27,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6555it [52:28,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

6556it [52:29,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6557it [52:30,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6558it [52:31,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6559it [52:32,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6560it [52:33,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6561it [52:34,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6562it [52:35,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6563it [52:36,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6564it [52:37,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6565it [52:38,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6566it [52:39,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6567it [52:40,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6568it [52:41,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step

6569it [52:42,  1.17s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6570it [52:44,  1.23s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6571it [52:45,  1.19s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6572it [52:46,  1.14s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

6573it [52:47,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6574it [52:48,  1.10s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

6575it [52:49,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6576it [52:51,  1.16s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

6577it [52:51,  1.10s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6578it [52:53,  1.10s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

6579it [52:54,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6580it [52:55,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6581it [52:56,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

6582it [52:57,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6583it [52:57,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6584it [52:58,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6585it [52:59,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6586it [53:00,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6587it [53:01,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6588it [53:02,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6589it [53:03,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6590it [53:04,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6591it [53:05,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6592it [53:06,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6593it [53:07,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6594it [53:08,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6595it [53:09,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6596it [53:10,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6597it [53:11,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6598it [53:12,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6599it [53:13,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6600it [53:14,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6601it [53:15,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6602it [53:16,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6603it [53:17,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6604it [53:18,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6605it [53:19,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6606it [53:20,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6607it [53:21,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6608it [53:22,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6609it [53:23,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6610it [53:24,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6611it [53:25,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6612it [53:25,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6613it [53:26,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6614it [53:27,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6615it [53:28,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6616it [53:29,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6617it [53:30,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6618it [53:31,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6619it [53:32,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6620it [53:33,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6621it [53:34,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6622it [53:35,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6623it [53:36,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6624it [53:37,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6625it [53:38,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6626it [53:39,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6627it [53:40,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6628it [53:41,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step

6629it [53:42,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6630it [53:43,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6631it [53:44,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6632it [53:45,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6633it [53:46,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6634it [53:47,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6635it [53:48,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6636it [53:49,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6637it [53:50,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6638it [53:51,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6639it [53:52,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6640it [53:53,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6641it [53:54,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6642it [53:55,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6643it [53:56,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6644it [53:57,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6645it [53:58,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6646it [53:59,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6647it [53:59,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6648it [54:00,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6649it [54:02,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6650it [54:03,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

6651it [54:04,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6652it [54:05,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6653it [54:06,  1.13s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6654it [54:07,  1.10s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

6655it [54:08,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

6656it [54:10,  1.13s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6657it [54:11,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6658it [54:12,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6659it [54:13,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6660it [54:14,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6661it [54:15,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6662it [54:16,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6663it [54:17,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6664it [54:17,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6665it [54:18,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6666it [54:19,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6667it [54:20,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6668it [54:21,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6669it [54:22,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6670it [54:23,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6671it [54:24,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6672it [54:25,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6673it [54:26,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6674it [54:27,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6675it [54:28,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6676it [54:29,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6677it [54:30,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6678it [54:31,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6679it [54:32,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6680it [54:33,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step

6681it [54:34,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6682it [54:35,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6683it [54:36,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6684it [54:37,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6685it [54:38,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6686it [54:39,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6687it [54:40,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6688it [54:41,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6689it [54:42,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6690it [54:43,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6691it [54:44,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6692it [54:45,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6693it [54:46,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6694it [54:47,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6695it [54:48,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6696it [54:49,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6697it [54:50,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6698it [54:51,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6699it [54:52,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6700it [54:53,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6701it [54:54,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6702it [54:55,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6703it [54:56,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6704it [54:57,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6705it [54:58,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6706it [54:59,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6707it [55:00,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6708it [55:00,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6709it [55:02,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6710it [55:03,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6711it [55:04,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6712it [55:05,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6713it [55:06,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6714it [55:07,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6715it [55:08,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6716it [55:09,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6717it [55:10,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6718it [55:10,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6719it [55:11,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6720it [55:12,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6721it [55:13,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6722it [55:14,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6723it [55:15,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6724it [55:16,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6725it [55:17,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6726it [55:18,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

6727it [55:19,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6728it [55:20,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6729it [55:21,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6730it [55:22,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6731it [55:23,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6732it [55:24,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6733it [55:25,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6734it [55:26,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6735it [55:27,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6736it [55:28,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6737it [55:29,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6738it [55:30,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6739it [55:31,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6740it [55:32,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6741it [55:33,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6742it [55:34,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6743it [55:35,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6744it [55:36,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6745it [55:37,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6746it [55:38,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6747it [55:38,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6748it [55:39,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6749it [55:40,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

6750it [55:41,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6751it [55:43,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6752it [55:44,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6753it [55:45,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6754it [55:45,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6755it [55:46,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6756it [55:47,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6757it [55:48,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6758it [55:49,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

6759it [55:50,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6760it [55:51,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6761it [55:52,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6762it [55:53,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6763it [55:54,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6764it [55:55,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6765it [55:56,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6766it [55:57,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6767it [55:58,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6768it [55:59,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6769it [56:00,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6770it [56:01,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6771it [56:02,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6772it [56:03,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6773it [56:04,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6774it [56:05,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6775it [56:06,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6776it [56:07,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step

6777it [56:08,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6778it [56:09,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6779it [56:10,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6780it [56:11,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6781it [56:12,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6782it [56:13,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6783it [56:13,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6784it [56:14,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6785it [56:15,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6786it [56:16,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6787it [56:17,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6788it [56:18,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6789it [56:19,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6790it [56:20,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6791it [56:21,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

6792it [56:22,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6793it [56:23,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

6794it [56:25,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6795it [56:26,  1.13s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6796it [56:27,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6797it [56:28,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6798it [56:29,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6799it [56:30,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6800it [56:31,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6801it [56:32,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6802it [56:32,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6803it [56:34,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6804it [56:35,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6805it [56:36,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6806it [56:37,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6807it [56:38,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6808it [56:38,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6809it [56:39,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6810it [56:40,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

6811it [56:42,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6812it [56:43,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6813it [56:44,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6814it [56:45,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6815it [56:46,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6816it [56:47,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6817it [56:48,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6818it [56:48,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6819it [56:49,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6820it [56:50,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6821it [56:52,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6822it [56:53,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

6823it [56:54,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6824it [56:55,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

6825it [56:56,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6826it [56:56,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

6827it [56:57,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

6828it [56:59,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

6829it [56:59,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

6830it [57:00,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

6831it [57:01,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6832it [57:02,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6833it [57:03,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6834it [57:04,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6835it [57:05,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6836it [57:06,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step

6837it [57:07,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6838it [57:09,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

6839it [57:10,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

6840it [57:11,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

6841it [57:12,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6842it [57:13,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6843it [57:14,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6844it [57:15,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6845it [57:16,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

6846it [57:17,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6847it [57:18,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6848it [57:19,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6849it [57:20,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6850it [57:21,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6851it [57:22,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step

6852it [57:23,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6853it [57:24,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6854it [57:25,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

6855it [57:26,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6856it [57:27,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6857it [57:28,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6858it [57:29,  1.07s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6859it [57:30,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6860it [57:31,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6861it [57:32,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6862it [57:33,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

6863it [57:34,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6864it [57:35,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6865it [57:36,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

6866it [57:37,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

6867it [57:38,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6868it [57:39,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

6869it [57:40,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6870it [57:41,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step

6871it [57:42,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6872it [57:44,  1.17s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6873it [57:45,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

6874it [57:46,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

6875it [57:47,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6876it [57:48,  1.15s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6877it [57:49,  1.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

6878it [57:50,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6879it [57:51,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6880it [57:52,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6881it [57:53,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6882it [57:54,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6883it [57:55,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6884it [57:56,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6885it [57:57,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6886it [57:58,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6887it [57:59,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6888it [58:00,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6889it [58:01,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6890it [58:02,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

6891it [58:03,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6892it [58:05,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6893it [58:06,  1.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6894it [58:07,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

6895it [58:07,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6896it [58:08,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6897it [58:09,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6898it [58:10,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6899it [58:11,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

6900it [58:12,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6901it [58:14,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6902it [58:14,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6903it [58:15,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6904it [58:16,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6905it [58:17,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6906it [58:18,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6907it [58:19,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6908it [58:20,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6909it [58:21,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6910it [58:22,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6911it [58:23,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6912it [58:24,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

6913it [58:25,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6914it [58:26,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

6915it [58:27,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6916it [58:28,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6917it [58:29,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6918it [58:30,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6919it [58:31,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6920it [58:32,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6921it [58:33,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6922it [58:34,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6923it [58:35,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6924it [58:35,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6925it [58:36,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6926it [58:37,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6927it [58:39,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6928it [58:39,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6929it [58:40,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6930it [58:41,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

6931it [58:42,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

6932it [58:43,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6933it [58:44,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6934it [58:45,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6935it [58:46,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6936it [58:47,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6937it [58:48,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6938it [58:49,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6939it [58:50,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6940it [58:51,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6941it [58:52,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6942it [58:53,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6943it [58:54,  1.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6944it [58:55,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6945it [58:56,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6946it [58:57,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6947it [58:58,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

6948it [58:58,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

6949it [58:59,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

6950it [59:01,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6951it [59:02,  1.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6952it [59:03,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6953it [59:04,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6954it [59:05,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6955it [59:06,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6956it [59:07,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6957it [59:08,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

6958it [59:09,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

6959it [59:10,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6960it [59:11,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6961it [59:12,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6962it [59:13,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6963it [59:14,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6964it [59:15,  1.08s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6965it [59:16,  1.09s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6966it [59:17,  1.05s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6967it [59:18,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6968it [59:19,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6969it [59:20,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6970it [59:21,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6971it [59:22,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

6972it [59:23,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6973it [59:24,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6974it [59:25,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

6975it [59:26,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6976it [59:27,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

6977it [59:28,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

6978it [59:29,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6979it [59:30,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

6980it [59:31,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6981it [59:32,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6982it [59:33,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

6983it [59:34,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

6984it [59:35,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

6985it [59:36,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6986it [59:36,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6987it [59:37,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

6988it [59:38,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6989it [59:39,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

6990it [59:40,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

6991it [59:41,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

6992it [59:42,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

6993it [59:43,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

6994it [59:44,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

6995it [59:45,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

6996it [59:46,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

6997it [59:47,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

6998it [59:48,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

6999it [59:49,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7000it [59:50,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7001it [59:51,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7002it [59:52,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7003it [59:53,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

7004it [59:54,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

7005it [59:55,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

7006it [59:56,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

7007it [59:57,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7008it [59:58,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

7009it [59:59,  1.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

7010it [1:00:00,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

7011it [1:00:01,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

7012it [1:00:02,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

7013it [1:00:03,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

7014it [1:00:04,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

7015it [1:00:05,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

7016it [1:00:06,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

7017it [1:00:07,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7018it [1:00:08,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

7019it [1:00:09,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

7020it [1:00:10,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7021it [1:00:11,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

7022it [1:00:12,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7023it [1:00:13,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

7024it [1:00:14,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

7025it [1:00:15,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7026it [1:00:16,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

7027it [1:00:16,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7028it [1:00:17,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

7029it [1:00:18,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

7030it [1:00:19,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7031it [1:00:20,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7032it [1:00:21,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7033it [1:00:23,  1.03s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

7034it [1:00:23,  1.00s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

7035it [1:00:24,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7036it [1:00:25,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7037it [1:00:26,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7038it [1:00:27,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7039it [1:00:28,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7040it [1:00:29,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

7041it [1:00:30,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

7042it [1:00:31,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7043it [1:00:32,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7044it [1:00:33,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7045it [1:00:34,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7046it [1:00:35,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

7047it [1:00:36,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7048it [1:00:37,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

7049it [1:00:38,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7050it [1:00:39,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7051it [1:00:40,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

7052it [1:00:41,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

7053it [1:00:42,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

7054it [1:00:43,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7055it [1:00:44,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7056it [1:00:45,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7057it [1:00:46,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

7058it [1:00:47,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7059it [1:00:48,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

7060it [1:00:49,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7061it [1:00:49,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

7062it [1:00:50,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step

7063it [1:00:51,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

7064it [1:00:52,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7065it [1:00:53,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

7066it [1:00:54,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7067it [1:00:55,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

7068it [1:00:56,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

7069it [1:00:57,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7070it [1:00:58,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7071it [1:00:59,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

7072it [1:01:00,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

7073it [1:01:01,  1.01s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

7074it [1:01:02,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7075it [1:01:03,  1.02s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

7076it [1:01:04,  1.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

7077it [1:01:05,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7078it [1:01:06,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

7079it [1:01:07,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

7080it [1:01:08,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7081it [1:01:09,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

7082it [1:01:10,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7083it [1:01:11,  1.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

7084it [1:01:12,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7085it [1:01:13,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7086it [1:01:14,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7087it [1:01:15,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

7088it [1:01:15,  1.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7089it [1:01:16,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

7090it [1:01:17,  1.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step

7091it [1:01:18,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

7092it [1:01:19,  1.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

7093it [1:01:20,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

7094it [1:01:21,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

7095it [1:01:22,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

7096it [1:01:23,  1.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

7097it [1:01:24,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

7098it [1:01:25,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

7099it [1:01:26,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

7115it [1:01:27,  1.93it/s]

In [46]:
cards['card type encoded'] = cards['card type'].astype('category').cat.codes

In [45]:
cards

,class index,filepaths,labels,card type,data set,suit,labels_encoded,type,type suit,final_label,features,extracted_label,card type encoded
0,0,train/ace of clubs/001.jpg,ace of clubs,ace,train,clubs,0,number,number clubs,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.0,0
1,0,train/ace of clubs/002.jpg,ace of clubs,ace,train,clubs,0,number,number clubs,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.02084561, 0.552028...",0.0,0
2,0,train/ace of clubs/003.jpg,ace of clubs,ace,train,clubs,0,number,number clubs,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.091402613, 0....",0.0,0
3,0,train/ace of clubs/004.jpg,ace of clubs,ace,train,clubs,0,number,number clubs,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02104898, 0.0...",0.0,0
4,0,train/ace of clubs/005.jpg,ace of clubs,ace,train,clubs,0,number,number clubs,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7110,52,valid/two of spades/1.jpg,two of spades,two,valid,spades,52,number,number spades,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",12.0,12
7111,52,valid/two of spades/2.jpg,two of spades,two,valid,spades,52,number,number spades,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",12.0,12
7112,52,valid/two of spades/3.jpg,two of spades,two,valid,spades,52,number,number spades,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",12.0,12
7113,52,valid/two of spades/4.jpg,two of spades,two,valid,spades,52,number,number spades,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",12.0,12
7114,52,valid/two of spades/5.jpg,two of spades,two,valid,spades,52,number,number spades,number,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",12.0,12

In [41]:
cards.to_csv('cards/processed_cards.csv', index=False)

In [43]:
cards_no_features = cards[cards['features'].isnull()]
cards = cards[cards['features'].notnull()]

In [46]:
cards_no_features

,class index,filepaths,labels,card type,data set,suit,labels_encoded,type,type suit,final_label,features,extracted_label,card type encoded
120,0,train/ace of clubs/output,ace of clubs,ace,train,clubs,0,number,number clubs,number,None,NaN,0

In [47]:
cards.to_csv('cards/featured_cards.csv', index=False)